### ISSUE TITLE
Chain prop type can't be null at all the Social Recovery components!

### ISSUE THREAD

**Issue by AMIRKHANEF** [Nick-1979/polkadot-Js-Plus-extension#45]
Social recovery only exist on kusama and westend, and because it is checked which chain the account is on, so The chain prop type on all the components related to the social recovery can not be null!

**Comment by Nick-1979** [comment]
look at [here]( https://github.com/Nick-1979/polkadot-Js-Plus-extension/blob/a8969460ce7202f0c46739717e6b5d28925af651/packages/extension-plus/src/Popup/SocialRecovery/index.tsx#L48)

chain might be null.

**Comment by AMIRKHANEF** [comment]
Right.
But I can list the problems it can cause if it's not stopped in the first place (index page of social recovery component).

**Comment by AMIRKHANEF** [comment]
To avoid **null chain** problems, we need to add some **extra conditions** which makes the code **messy** and **complicated**!
In my mind, the **simplest** and **easiest** way is to stop it on the first page (**Index**).
And since the chain can be changed manually from **URL** of the page ,a **useEffect** can be used to track the **genesisHash** change.

**Comment by AMIRKHANEF** [comment]
In this case, if an **incorrect** genesisHash is entered in the URL (which **nullifies** the chain prop), the user **will not be allowed** to use social recovery.
Or if the entered genesisHash belongs to a **different chain**, it can use the social recovery if it be **is available** on that chain.

**Comment by AMIRKHANEF** [comment]
> In this case, if an **incorrect** genesisHash is entered in the URL (which **nullifies** the chain prop), the user **will not be allowed** to use social recovery. Or if the entered genesisHash belongs to a **different chain**, it can use the social recovery if it be **is available** on that chain.

#52
