### ISSUE TITLE
Proposals tab at Democracy component, sometimes has trouble to showing the proposal's deposited amount! 

### ISSUE THREAD

**Issue by AMIRKHANEF** [Nick-1979/polkadot-Js-Plus-extension#51]
At [this line](https://github.com/Nick-1979/polkadot-Js-Plus-extension/blob/ac09aec9d6abff55432230753bd12556baf4df0c/packages/extension-plus/src/Popup/Governance/Democracy/proposals/overview.tsx#L109), Because the proposal's image prop can be undefined, It's better to check before passing to a function!

**Comment by PolkaGate** [comment]
Did you applied the latest updates?

**Comment by AMIRKHANEF** [comment]
Ahh, you fixed it, I was a little late in submitting the issue!
Great👍🏻
