### ISSUE TITLE
Recovery friends don't get cached in the Social Recovery Configuration

### ISSUE THREAD

**Issue by takahser** [Nick-1979/polkadot-Js-Plus-extension#67]
When configuring social recovery _(Social Recovery > Configure my Account > Configure)_ and adding the Recovery friends, the Addresses are lost if navigating from the *Configuration* to the *Info* tab and back. Also, the other parameters are reset.

![polkadotjs-plus-bug](https://user-images.githubusercontent.com/5393704/189644654-7db73f72-ede6-4e46-99b4-0a6d91bd10e2.gif)

**Comment by Nick-1979** [comment]
Hi @takahser 

Thank you for the report.
This issue is fixed, plus UI recommendations are applied.


Cheers,
   Kami
